version: 2.1
jobs:
  build:
    working_directory: ~/src
    docker:
      - image: cimg/php:8.1-node
    steps:
      - checkout
      - run: sudo composer self-update --2
      - run:
          working_directory: src
          command: composer install -n --prefer-dist
      - run: npm ci
      - run: npm run dev
      - run:
          name: php test
          command: vendor/bin/phpunit