version: 2.1
jobs:
  build:
    working_directory: ~/src
    docker:
      - image: cimg/php:8.1-node
      - image: mysql:8.0.35
        environment:
          MYSQL_ROOT_PASSWORD: root  # MySQLのrootパスワード
          MYSQL_DATABASE: demo_test    # テスト用のデータベース名
    steps:
      - checkout
      - run: sudo composer self-update --2
      - restore_cache:
          key: composer-v2-{{ checksum "composer.lock" }}
      - run:
          command: composer install -n --prefer-dist
          working_directory: src
      - save_cache:
          key: composer-v2-{{ checksum "composer.lock" }}
          paths:
            - vendor
      - restore_cache:
          key: npm-v2-{{ checksum "package-lock.json" }}
      - run:
          name: npm ci
          command: |
            if [ ! -d node_modules ]; then
              npm ci
            fi
          working_directory: src
      - save_cache:
          key: npm-v1-{{ checksum "package-lock.json" }}
          paths:
            - node_modules
      - run:
          command: npm run dev
          working_directory: src
      # - run:
      #     name: Wait for MySQL to be ready
      #     command: |
      #       for i in `seq 1 60`; do
      #         nc -z mysql 3306 && echo Success && exit 0
      #         echo -n .
      #         sleep 2
      #       done
      #       echo "MySQL failed to start" && exit 1
      - run: ls
      - run:
          name: php test
          command: |
            php artisan migrate --env=testing  # テスト用データベースのマイグレーション
            vendor/bin/phpunit
          working_directory: src
          timeout: 20m