version: 2.1
jobs:
  build:
    working_directory: ./src
    docker:
      - image: cimg/php:8.1-node
      - image: mysql:8.0.35
        environment:
          MYSQL_ROOT_PASSWORD: root  # MySQLのrootパスワード
          MYSQL_DATABASE: demo_test    # テスト用のデータベース名
    environment:
      - DB_HOST: 127.0.0.1
    steps:
      - checkout
      - run: sudo composer self-update --2
      - restore_cache:
          key: composer-v2-{{ checksum "./src/composer.lock" }}
      - run:
          command: composer install -n --prefer-dist
          working_directory: ./src
      - save_cache:
          key: composer-v2-{{ checksum "./src/composer.lock" }}
          paths:
            - vendor
      - run: ls
      - restore_cache:
          key: npm-v2-{{ checksum "./src/package-lock.json" }}
      - run:
          name: npm ci
          command: |
            if [ ! -d node_modules ]; then
              npm ci
            fi
          working_directory: ./src
      - save_cache:
          key: npm-v1-{{ checksum "./src/package-lock.json" }}
          paths:
            - node_modules
      - run:
          command: npm run dev
          working_directory: ./src
      - run:
          name: Prepare PHP environment
          command: |
            sudo apt update
            sudo docker-php-ext-install zip pdo_mysql
      - run:
          name: Execute tests
          command: |
            php ./src/artisan --env=testing
            php ./src/vendor/bin/phpunit --configuration=./src/phpunit.xml