version: 2.1
jobs:
  build:
    working_directory: ~/src
    docker:
      - image: cimg/php:8.1-node
    steps:
      - checkout
      - run: sudo composer self-update --2
      - run:
          command: composer install -n --prefer-dist
          working_directory: src
      - run:
          command: npm ci
          working_directory: src
      - run:
          command: npm run dev
          working_directory: src
      - run:
          name: php test
          command: vendor/bin/phpunit
          working_directory: src          