version: 2.1
jobs:
  build:
    working_directory: ~/src
    docker:
      - image: cimg/php:8.1-node
      - image: mysql:8.0.35
        environment:
          DB_HOST: mysql
          MYSQL_ROOT_PASSWORD: root  # MySQLのrootパスワード
          MYSQL_DATABASE: demo_test    # テスト用のデータベース名
    steps:
      - checkout
      - run: sudo composer self-update --2
      - run:
          command: composer install -n --prefer-dist
          working_directory: src
      - run:
          command: npm ci
          working_directory: src
      - run:
          command: npm run dev
          working_directory: src
      - run:
          name: Wait for MySQL to be ready
          command: |
            for i in `seq 1 60`; do
              nc -z mysql 3306 && echo Success && exit 0
              echo -n .
              sleep 1
            done
            echo "MySQL failed to start" && exit 1
      - run:
          name: php test
          command: |
            php artisan migrate --env=testing  # テスト用データベースのマイグレーション
            vendor/bin/phpunit
          working_directory: src